---
- name: install dependencies packages
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - make

- name: create redis group
  group: name={{ redis_group }} system=yes state=present

- name: add redis user
  user: name={{ redis_user }} comment="Redis" home={{ redis_home }} group={{ redis_group }}
        shell=/bin/false system=yes state=present

- name: download redis
  get_url: url="{{ redis_download_url }}/{{ redis_package }}.tar.gz"
           dest={{ redis_download_dir }}/{{ redis_package }}.tar.gz

- name: extraction redis
  unarchive: src={{ redis_download_dir }}/{{ redis_package }}.tar.gz
             dest={{ redis_download_dir }} copy=no
             creates={{ redis_download_dir }}/{{ redis_package }}

- name: compile & install redis
  command: >
          {{ item }}
          chdir={{ redis_download_dir }}/{{ redis_package }}
          creates=/usr/local/bin/redis-server
  with_items:
    - make
    - make install

- name: create log & pidfile dir
  file: path={{ item }} state=directory owner={{ redis_user }} group=root mode=0755
  with_items:
    - "{{ redis_log_dir }}"
    - "{{ redis_pidfile_dir }}"

- name: add sysconfig/redis
  template: src=sysconfig/redis.j2 dest=/etc/sysconfig/redis owner=root group=root mode=0644

- include: server.yml
  when: redis_role == "server"

- include: sentinel.yml
  when: redis_role == "sentinel"