---
- name: add repository 'nginx'
  yum: name={{ nginx_repo_url }} state=present
  register: add_nginx_repo

- name: clean yum
  command: yum clean all
  when: add_nginx_repo.changed

- name: install nginx
  yum: name=nginx state=present
  register: nginx_install

- name: remove config dir
  file: path={{ nginx_conf_dir }} state=absent
  when: nginx_install.changed

- name: create confing dir
  file: path={{ nginx_conf_dir }} state=directory owner=root group=root mode=0755

- name: create log dir
  file: path={{ nginx_log_dir }} state=directory owner={{ nginx_user }} group={{ nginx_group }} mode=0755

- name: update config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: update logrotate.d/nginx
  template: src=logrotate.d/nginx.j2 dest=/etc/logrotate.d/nginx owner=root group=root mode=0644