---
jdk_version: { major: 8, minor: 45, build: 14 }
jdk_install_dir: "/usr/java"
jdk_home: "/usr/java/default"
jdk_download_url: "http://download.oracle.com/otn-pub/java/jdk"
jdk_download_header: "Cookie:oraclelicense=accept-securebackup-cookie"