---
- name: install ffmpeg build package
  yum: name={{ item }} state=installed
  with_items:
    - "automake"
    - "bzip2"
    - "cmake"
    - "freetype-devel"
    - "gcc"
    - "gcc-c++"
    - "git"
    - "libtool"
    - "make"
    - "mercurial"
    - "nasm"
    - "pkgconfig"
    - "zlib-devel"

- name: cretate ffmpeg source & prefix dir
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - "{{ ffmpeg_src_dir }}"
    - "{{ ffmpeg_prefix_dir }}"

- name: set PKG_CONFIG_PATH
  command: 'export PKG_CONFIG_PATH="{{ ffmpeg_prefix_dir }}/lib/pkgconfig"'

- name: install yasm
  include: yasm.yml

- name: install libx264
  include: libx264.yml

- name: install libx265
  include: libx265.yml

- name: install libfdk-aac
  include: libfdk-aac.yml

- name: install libmp3lame
  include: libmp3lame.yml

- name: install libopus
  include: libopus.yml

- name: install libogg
  include: libogg.yml

- name: install libvorbis
  include: libvorbis.yml

- name: install libtheora
  include: libtheora.yml

- name: install libvpx
  include: libvpx.yml

- name: download ffmpeg
  get_url: url="{{ ffmpeg_download_url }}/ffmpeg-{{ ffmpeg_version }}.tar.bz2"
           dest={{ ffmpeg_src_dir }}/ffmpeg-{{ ffmpeg_version }}.tar.bz2

- name: extraction ffmpeg
  unarchive: src={{ ffmpeg_src_dir }}/ffmpeg-{{ ffmpeg_version }}.tar.bz2
             dest={{ ffmpeg_src_dir }} copy=no creates={{ ffmpeg_src_dir }}/ffmpeg-{{ ffmpeg_version }}

- name: compile & install ffmpeg
  command: >
           {{ item }}
           chdir={{ ffmpeg_src_dir }}/ffmpeg-{{ ffmpeg_version }}
           creates={{ ffmpeg_bin_dir }}/ffmpeg
  with_items:
    - './configure --prefix="{{ ffmpeg_prefix_dir }}" --extra-cflags="-I{{ ffmpeg_prefix_dir }}/include" --extra-ldflags="-L{{ ffmpeg_prefix_dir }}/lib" --bindir="{{ ffmpeg_bin_dir }}" --pkg-config-flags="--static" {{ ffmpeg_enable_options | join(" ") }}'
    - "make -j{{ ansible_processor_count }}"
    - "make install"
    - "make clean"