---
redis_user: "redis"
redis_home: "/var/lib/redis"
redis_version: "3.0.7"
redis_download_dir: "/usr/local/src"
redis_role: "server" # server or sentinel
redis_ulimit: 65536
redis_sentinel_use: false
redis_sentinel_private_key: "id_rsa"
redis_sentinel_public_key: "id_rsa.pub"

# redis.conf
## INCLUDES
#redis_include: /path/to/local.conf
## GENERAL
redis_daemonize: "yes"
redis_pidfile: "/var/run/redis/redis.pid"
redis_port: 6379
redis_backlog: 511
redis_bind: "0.0.0.0"
redis_timeout: 0
redis_tcp_keepalive: 0
redis_loglevel: "notice"
redis_logfile: "/var/log/redis/redis.log"
redis_database: 16
## SNAPSHOTTING
redis_save:
  - "900 1"
  - "300 10"
  - "60 10000"
redis_stop_writes_on_bgsave_error: "yes"
redis_rdbcompression: "yes"
redis_rdbchecksum: "yes"
redis_dbfilename: "dump.rdb"
redis_data_dir: "/var/lib/redis/"
## REPLICATION
redis_slaveof: false
redis_master_ip: "127.0.0.1"
redis_master_port: 6379
#redis_master_auth:
redis_slave_serve_stale_data: "yes"
redis_slave_read_only: "yes"
redis_repl_ping_slave_period: 10
redis_repl_timeout: 60
redis_repl_disable_tcp_nodelay: "no"
redis_slave_priority: 100
## SECURITY
#redis_requirepass:
## LIMITS
redis_maxclients: 10000
redis_maxmemory: "{{ (ansible_memtotal_mb * 0.4) | round | int }}mb"
redis_maxmemory_policy: "volatile-lru"
redis_maxmemory_samples: 3
## APPEND ONLY MODE
redis_appendonly: "no"
redis_appendfilename: "appendonly.aof"
redis_appendfsync: "everysec"
redis_no_appendfsync_on_rewrite: "no"
redis_auto_aof_rewrite_percentage: 100
redis_auto_aof_rewrite_min_size: "64mb"
## LUA SCRIPTING
redis_lua_time_limit: 5000
## SLOW LOG
redis_slowlog_log_slower_than: 10000
redis_slowlog_max_len: 1024
## Event notification
redis_notify_keyspace_events: ""
## ADVANCED CONFIG
redis_hash_max_ziplist_entries: 512
redis_hash_max_ziplist_value: 64
redis_list_max_ziplist_entries: 512
redis_list_max_ziplist_value: 64
redis_set_max_intset_entries: 512
redis_zset_max_ziplist_entries: 128
redis_zset_max_ziplist_value: 64
redis_hll_sparse_max_bytes: 3000
redis_activerehashing: "yes"
redis_client_output_buffer_limit: { normal: "0 0 0", slave: "0 0 0", pubsub: "32mb 8mb 60" }
redis_hz: 10
redis_aof_rewrite_incremental_fsync: "yes"

# redis-sentinel.conf
redis_sentinel_port: 26379
redis_sentinel_bind: "0.0.0.0"
redis_sentinel_daemonize: "yes"
redis_sentinel_pidfile: "/var/run/redis/redis-sentinel.pid"
redis_sentinel_loglevel: "notice"
redis_sentinel_logfile: "/var/log/redis/redis-sentinel.log"
redis_sentinel_master_name: "mymaster"
redis_sentinel_master_ip: "127.0.0.1"
redis_sentinel_master_port: 6379
redis_sentinel_quorum: 1
#redis_sentinel_auth_pass:
redis_sentinel_down_after_milliseconds: 30000
redis_sentinel_parallel_syncs: 1
redis_sentinel_failover_timeout: 180000
#redis_sentinel_notification_script:
redis_sentinel_client_reconfig_script: "/etc/redis/sentinel_failover.sh"

# sentinel_failover.sh
redis_sentinel_vip: "127.0.0.1"
redis_sentinel_vip_prefix: "32"