---
elasticsearch_version: "5.1.1-1"
elasticsearch_user: "elasticsearch"
elasticsearch_group: "elasticsearch"
elasticsearch_home: "/usr/share/elasticsearch"
elasticsearch_conf_dir: "/etc/elasticsearch"
elasticsearch_template_dir: "{{ elasticsearch_conf_dir }}/templates"
elasticsearch_data_dir: "/var/lib/elasticsearch"
elasticsearch_log_dir: "/var/log/elasticsearch"
elasticsearch_pid_dir: "/var/run/elasticsearch"
elasticsearch_plugin_bin: "{{ elasticsearch_home }}/bin/elasticsearch-plugin"
elasticsearch_templates:
  - "path"

# sysconfig/elasticsearch
elasticsearch_restart_on_upgrade: "false"
elasticsearch_startup_sleep_time: 5
elasticsearch_max_open_files: 65536
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_max_map_count: 262144

# elasticsearch.yml
## Cluster
elasticsearch_cluster_name: "elasticsearch"
## Node
elasticsearch_node_name: "{{ inventory_hostname }}"
## Memory
elasticsearch_bootstrap_memory_lock: "true"
## Network
elasticsearch_network_host: "0.0.0.0"
elasticsearch_http_port: 9200
## Discovery
elasticsearch_discovery_zen_ping_unicast_hosts: "[\"127.0.0.1\", \"[::1]\"]"
elasticsearch_discovery_zen_minimum_master_nodes: 1
## Various
elasticsearch_node_max_local_storage_nodes: 1
## X-Pack
elasticsearch_xpack_security_enabled: "false"
elasticsearch_xpack_graph_enabled: "false"

# jvm.options
elasticsearch_jvm_heap_xms: "{{ (ansible_memtotal_mb * 0.5) | round | int }}m"
elasticsearch_jvm_heap_xmx: "{{ (ansible_memtotal_mb * 0.5) | round | int }}m"

# templates/path.json
elasticsearch_path_template: "status_monitor-*"