---
- name: import public signing key
  rpm_key: key=https://packages.elastic.co/GPG-KEY-elasticsearch

- name: add repository 'curator'
  copy: src=curator.repo dest=/etc/yum.repos.d/curator.repo owner=root group=root mode=0644

- name: install python-elasticsearch-curator
  yum: name=elasticsearch-curator-{{ curator_version }} state=present

- name: add cron 'curator close job'
  cron: name="curator close job"
        job="/usr/bin/curator --host {{ curator_host }} close indices --older-than {{ curator_close_older_than }} --time-unit {{ curator_close_time_unit }} --timestring {{ curator_close_timestring }}"
        minute={{ curator_close_cron_minute }} hour={{ curator_close_cron_hour }} user=cy_daemon state=present

- name: add cron 'curator delete job'
  cron: name="curator delete job"
        job="/usr/bin/curator --host {{ curator_host }} delete indices --older-than {{ curator_delete_older_than }} --time-unit {{ curator_delete_time_unit }} --timestring {{ curator_delete_timestring }}"
        minute={{ curator_delete_cron_minute }} hour={{ curator_delete_cron_hour }} user=cy_daemon state=present
